### ISSUE TITLE
Differential Drive

### ISSUE THREAD

**Issue by David9696** [JuliusSustarevas/ArmStone#4]
Hi,

Thanks for sharing this project. I am testing this package by setting base_controller to as_base_differential_controller.

With gazebo, I realized that the odometry seems not very accurate. Seems like there is a delay.

Is this behavior expected? Do I need to change anything for simulation with as_base_differential_controller?

Thanks.

**Comment by JuliusSustarevas** [comment]
Hey sorry I'm not really planning on maintaining this to the extent that i can be used off the shelf by others. 
I've mostly used the mecanum drive and put the diff drive just for modularity as a first step.  

as_base_differential_controller should just setup the the normal ROS diff drive controller. If you are having odometry issues it is likely that the wheel modeling is not very suited for diff drive assumptions.  Note that here I'm using spheres that rotate at an angle in order to model mecanum wheels. So perhaps that's the cause. Also if you are loading the arm on there as well, make sure it doesn't collide into the ground as it will obviously cause friction and make the base slip.

**Comment by David9696** [comment]
Hi,

No problem. Thanks for sharing this great project.
